version: '2'
services:
  zookeeper:
    image: ubuntu/zookeeper:edge
    ports:
      - "2181:2181"
  kafka:
    image: ubuntu/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      ZOOKEEPER_HOST: zookeeper
      ZOOKEEPER_PORT: 2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/demo.sh:/demo/demo.sh
      - ${PWD}/server.properties:/etc/kafka/server.properties
networks:
  default:
    name: qotd
    external: true
    
      
